#!/usr/bin/env bash
# Test Fortran expression lowering by driving compilations
# and executions of programs generated by expr-test-generation.cc
#   usage: cmd llvm_build_directory

LLVM=$1
BBC=$LLVM/bin/bbc
LLC=$LLVM/bin/llc
CPP=g++
FCC=pgfortran # So far, only works with pgfortran because of pgmath linking.
FCC_OPTIONS="-Kieee" # That is required because bit to bit compare so far.
SRC=$PWD/expr-test-generator.cc

function die {
  echo "$(basename $0): $*" >&2
  exit 1
}

temp=`mktemp -d ./tmp.XXXXXX`
cd $temp
[[ $KEEP ]] || trap "cd .. && rm -rf $temp" EXIT

testGen=./genTests
testFile=test.f90
driverFile=driver.f90
bbcLog=bbc.log
assembly=a.s
testObject=test.o
testExec=./test_exec
testLog=test.log

$CPP $SRC -std=c++17 -o $testGen
[[ $? -ne 0 ]] && die "test generator compilation failure"
$testGen 1>$testFile 2>$driverFile
[[ $? -ne 0 ]] && die "test generation failure"
$BBC $testFile 2>$bbcLog
[[ $? -ne 0 ]] && die "bbc test.f90 compilation failure"
$LLC a.ll -o $assembly
[[ $? -ne 0 ]] && die "llc failed compiling bbc output"
as $assembly -o $testObject
[[ $? -ne 0 ]] && die "as failed compiling llc output"
$FCC $testObject $driverFile -o $testExec $FCC_OPTIONS
[[ $? -ne 0 ]] && die "driver.f90 compilation/linking failure"
$testExec > $testLog
result=$?
cat $testLog
if [ $result -ne 0 ]; then
  echo "FAIL"
else
  echo "PASS"
fi
